/* funcionalidad arrastrar y soltar tareas en las columnas */

/* const prueba = document.querySelectorAll("container__columns");

new Sortable(toDo, {
  group: 'shared', // set both lists to same group
  animation: 150
});

new Sortable(inProgress, {
  group: 'shared',
  animation: 150
});

new Sortable(completed, {
  group: 'shared',
  animation: 150
}); */

/* cerrar funcionalidad arrastrar y soltar tareas en las columnas */